// backend/controllers/aicontrollers.js
const axios = require('axios');

/**
 * Send resume text to Hugging Face for analysis using Mistral-7B-Instruct.
 * @param {string} text – The plain-text contents of the resume.
 * @returns {Promise<Object>} – The feedback generated by the model.
 * @throws Will throw an error if the API request fails or no text is provided.
 */
async function analyzeText(text) {
  if (!text || !text.trim()) {
    throw new Error('No resume text provided');
  }

  const apiUrl = 'https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.1';

  try {
    const response = await axios.post(
      apiUrl,
      {
        inputs: `You are a professional resume reviewer. Provide actionable feedback on this resume:\n\n${text}`,
      },
      {
        headers: {
          Authorization: `Bearer ${process.env.HUGGINGFACE_API_KEY}`,
          'Content-Type': 'application/json',
        },
      }
    );

    const output = response.data?.[0]?.generated_text || 'No feedback received.';
    return { feedback: output };
  } catch (error) {
    console.error('Error calling Hugging Face API:', error.response?.data || error.message);
    throw new Error('Failed to analyze text via Hugging Face API');
  }
}

module.exports = { analyzeText };
